# GitLab CI Runner configuration file
# By Thanh Nguyen <btnguyen2k@gmail.com>

#cache:

variables:
  DIR_DEPLOY: $CI_PROJECT_NAME

before_script:
  - whoami && pwd && date
  - "export CI_PROJECT_VERSION=`echo $CI_COMMIT_REF_NAME | cut -d'-' -f 2`"
  - "echo CI_PROJECT_VERSION: $CI_COMMIT_REF_NAME --\\> $CI_PROJECT_VERSION"
  - "export CI_PROJECT_DEPLOY_DIR=$DIR_DEPLOY/$CI_PROJECT_NAME-$CI_PROJECT_VERSION"
  - "echo CI_PROJECT_DEPLOY_DIR: $CI_PROJECT_DEPLOY_DIR"

after_script:

stages:
  - build
  - test
  - docker-build
  - docker-release

build:
  stage: build
  script:
    - date
  tags:
    - gitlabci-build
    - golang

#test:
#  stage: test
#  only:
#    # Run ony if commit has tag release-x.y.z.t, staging-x.y.z.t, or test-x.y.z.t
#    - /^release-.*$/
#    - /^staging-.*$/
#    - /^test-.*$/
#  script:
#    - date
#    #- sbt -Djline.terminal=jline.UnsupportedTerminal test
#  tags:
#    - gitlabci-build
#    - java
#    - scom
#
#build docker image:
#  stage: docker-build
#  only:
#    - /^release-.*$/
#    - /^staging-.*$/
#    - /^test-.*$/
#  script:
#    - date
#    - sbt -Djline.terminal=jline.UnsupportedTerminal clean docker:stage
#    - docker build --force-rm --squash -t $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION ./target/docker/stage
#    - docker rmi $(docker images -f "dangling=true" -q)
#  tags:
#    - gitlabci-build
#    - java
#    - scom
#
#push test to docker registry:
#  stage: docker-release
#  only:
#    - /^test-.*$/
#  script:
#    - date
#    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_SERVER
#    - docker tag $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-test
#    - docker push $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-test
#  tags:
#    - gitlabci-build
#    - java
#    - scom
#  when: manual
#
#push staging to docker registry:
#  stage: docker-release
#  only:
#    - /^staging-.*$/
#  script:
#    - date
#    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_SERVER
#    - docker tag $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-staging
#    - docker push $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION-test
#  tags:
#    - gitlabci-build
#    - java
#    - scom
#  when: manual
#
#push release to docker registry:
#  stage: docker-release
#  only:
#    - /^release-.*$/
#  script:
#    - date
#    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_SERVER
#    - docker tag $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:latest
#    - docker push $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:$CI_PROJECT_VERSION
#    - docker push $DOCKER_REGISTRY_SERVER/$CI_PROJECT_NAME:latest
#  tags:
#    - gitlabci-build
#    - java
#    - scom
#  when: manual
